# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logIOT', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='log_time',
            new_name='time',
        ),
    ]
